server:
  port: 8090

spring:
  rabbitmq:
    host: 172.16.0.107
    port: 5672
    username: guest
    password: guest

authdb:
    url: jdbc:mysql://172.16.0.107:3306/tb_authdb?serverTimezone=UTC&useSSL=false
    user: newgw
    pass: pwnewgw
